18/09/2023 10:23:10: Error in register_atlas.py for sub-CC00058XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00058XX09 ses-11300 wang' returned non-zero exit status 1.
10/10/2023 20:01:11: Error in phase1_registration.py for sub-CC00119XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00119XX12 ses-39400 ' returned non-zero exit status 1.
10/10/2023 20:01:12: Error in phase1_registration.py for sub-CC00120XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00120XX05 ses-41600 ' returned non-zero exit status 1.
10/10/2023 20:01:12: Error in phase1_registration.py for sub-CC00121XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00121XX06 ses-41700 ' returned non-zero exit status 1.
10/10/2023 20:01:13: Error in phase1_registration.py for sub-CC00122XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00122XX07 ses-42000 ' returned non-zero exit status 1.
10/10/2023 20:01:13: Error in phase1_registration.py for sub-CC00124XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00124XX09 ses-42302 ' returned non-zero exit status 1.
10/10/2023 20:01:13: Error in phase1_registration.py for sub-CC00126XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00126XX11 ses-43100 ' returned non-zero exit status 1.
10/10/2023 20:01:14: Error in phase1_registration.py for sub-CC00127XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00127XX12 ses-43200 ' returned non-zero exit status 1.
10/10/2023 20:01:14: Error in phase1_registration.py for sub-CC00129AN14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00129AN14 ses-43500 ' returned non-zero exit status 1.
10/10/2023 20:01:15: Error in phase1_registration.py for sub-CC00129BN14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00129BN14 ses-43701 ' returned non-zero exit status 1.
10/10/2023 20:01:15: Error in phase1_registration.py for sub-CC00130XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00130XX07 ses-44001 ' returned non-zero exit status 1.
10/10/2023 20:01:16: Error in phase1_registration.py for sub-CC00131XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00131XX08 ses-44200 ' returned non-zero exit status 1.
10/10/2023 20:01:16: Error in phase1_registration.py for sub-CC00132XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00132XX09 ses-44400 ' returned non-zero exit status 1.
10/10/2023 20:01:17: Error in phase1_registration.py for sub-CC00133XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00133XX10 ses-44500 ' returned non-zero exit status 1.
10/10/2023 20:01:17: Error in phase1_registration.py for sub-CC00134XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00134XX11 ses-44600 ' returned non-zero exit status 1.
10/10/2023 20:01:18: Error in phase1_registration.py for sub-CC00135AN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00135AN12 ses-44900 ' returned non-zero exit status 1.
10/10/2023 20:01:18: Error in phase1_registration.py for sub-CC00135BN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00135BN12 ses-44704 ' returned non-zero exit status 1.
10/10/2023 20:01:19: Error in phase1_registration.py for sub-CC00136AN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00136AN13 ses-45100 ' returned non-zero exit status 1.
10/10/2023 20:01:19: Error in phase1_registration.py for sub-CC00136BN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00136BN13 ses-45000 ' returned non-zero exit status 1.
10/10/2023 20:01:19: Error in phase1_registration.py for sub-CC00138XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00138XX15 ses-46200 ' returned non-zero exit status 1.
10/10/2023 20:01:20: Error in phase1_registration.py for sub-CC00139XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00139XX16 ses-49101 ' returned non-zero exit status 1.
10/10/2023 20:01:20: Error in phase1_registration.py for sub-CC00143AN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00143AN12 ses-47501 ' returned non-zero exit status 1.
10/10/2023 20:01:21: Error in phase1_registration.py for sub-CC00143BN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00143BN12 ses-47600 ' returned non-zero exit status 1.
10/10/2023 20:01:21: Error in phase1_registration.py for sub-CC00144XX13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00144XX13 ses-47701 ' returned non-zero exit status 1.
10/10/2023 20:01:22: Error in phase1_registration.py for sub-CC00145XX14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00145XX14 ses-48100 ' returned non-zero exit status 1.
10/10/2023 20:01:22: Error in phase1_registration.py for sub-CC00146XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00146XX15 ses-48400 ' returned non-zero exit status 1.
10/10/2023 20:01:23: Error in phase1_registration.py for sub-CC00147XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00147XX16 ses-48500 ' returned non-zero exit status 1.
10/10/2023 20:01:23: Error in phase1_registration.py for sub-CC00149XX18: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00149XX18 ses-49000 ' returned non-zero exit status 1.
10/10/2023 20:01:24: Error in phase1_registration.py for sub-CC00150AN02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00150AN02 ses-54800 ' returned non-zero exit status 1.
10/10/2023 20:01:24: Error in phase1_registration.py for sub-CC00150BN02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00150BN02 ses-49100 ' returned non-zero exit status 1.
10/10/2023 20:01:25: Error in phase1_registration.py for sub-CC00152AN04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00152AN04 ses-49200 ' returned non-zero exit status 1.
10/10/2023 20:01:25: Error in phase1_registration.py for sub-CC00153XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00153XX05 ses-50300 ' returned non-zero exit status 1.
10/10/2023 20:01:25: Error in phase1_registration.py for sub-CC00154XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00154XX06 ses-50700 ' returned non-zero exit status 1.
10/10/2023 20:01:26: Error in phase1_registration.py for sub-CC00155XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00155XX07 ses-51300 ' returned non-zero exit status 1.
10/10/2023 20:01:26: Error in phase1_registration.py for sub-CC00156XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00156XX08 ses-51500 ' returned non-zero exit status 1.
10/10/2023 20:01:27: Error in phase1_registration.py for sub-CC00157XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00157XX09 ses-51900 ' returned non-zero exit status 1.
10/10/2023 20:01:27: Error in phase1_registration.py for sub-CC00158XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00158XX10 ses-52200 ' returned non-zero exit status 1.
10/10/2023 20:01:28: Error in phase1_registration.py for sub-CC00159XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00159XX11 ses-52600 ' returned non-zero exit status 1.
10/10/2023 20:01:28: Error in phase1_registration.py for sub-CC00160XX04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00160XX04 ses-52700 ' returned non-zero exit status 1.
10/10/2023 20:01:29: Error in phase1_registration.py for sub-CC00161XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00161XX05 ses-53100 ' returned non-zero exit status 1.
10/10/2023 20:01:29: Error in phase1_registration.py for sub-CC00162XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00162XX06 ses-53600 ' returned non-zero exit status 1.
11/10/2023 22:03:21: Error in phase1_registration.py for sub-CC00119XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00119XX12 ses-39400 ' returned non-zero exit status 1.
11/10/2023 22:03:22: Error in phase1_registration.py for sub-CC00120XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00120XX05 ses-41600 ' returned non-zero exit status 1.
11/10/2023 22:03:22: Error in phase1_registration.py for sub-CC00121XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00121XX06 ses-41700 ' returned non-zero exit status 1.
11/10/2023 22:04:20: Error in phase1_registration.py for sub-CC00119XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00119XX12 ses-39400 ' returned non-zero exit status 1.
11/10/2023 22:04:21: Error in phase1_registration.py for sub-CC00120XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/phase1_registration.py sub-CC00120XX05 ses-41600 ' returned non-zero exit status 1.
13/10/2023 00:46:41: Error in register_atlas.py for sub-CC00119XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00119XX12 ses-39400 wang' returned non-zero exit status 1.
13/10/2023 00:46:42: Error in register_atlas.py for sub-CC00120XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00120XX05 ses-41600 wang' returned non-zero exit status 1.
13/10/2023 00:46:43: Error in register_atlas.py for sub-CC00121XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00121XX06 ses-41700 wang' returned non-zero exit status 1.
13/10/2023 00:46:44: Error in register_atlas.py for sub-CC00122XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00122XX07 ses-42000 wang' returned non-zero exit status 1.
13/10/2023 00:46:45: Error in register_atlas.py for sub-CC00124XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00124XX09 ses-42302 wang' returned non-zero exit status 1.
13/10/2023 00:46:46: Error in register_atlas.py for sub-CC00126XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00126XX11 ses-43100 wang' returned non-zero exit status 1.
13/10/2023 00:46:47: Error in register_atlas.py for sub-CC00127XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00127XX12 ses-43200 wang' returned non-zero exit status 1.
13/10/2023 00:46:48: Error in register_atlas.py for sub-CC00129AN14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00129AN14 ses-43500 wang' returned non-zero exit status 1.
13/10/2023 00:46:50: Error in register_atlas.py for sub-CC00129BN14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00129BN14 ses-43701 wang' returned non-zero exit status 1.
13/10/2023 00:46:51: Error in register_atlas.py for sub-CC00130XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00130XX07 ses-44001 wang' returned non-zero exit status 1.
13/10/2023 00:46:52: Error in register_atlas.py for sub-CC00131XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00131XX08 ses-44200 wang' returned non-zero exit status 1.
13/10/2023 00:46:53: Error in register_atlas.py for sub-CC00132XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00132XX09 ses-44400 wang' returned non-zero exit status 1.
13/10/2023 00:46:54: Error in register_atlas.py for sub-CC00133XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00133XX10 ses-44500 wang' returned non-zero exit status 1.
13/10/2023 00:46:55: Error in register_atlas.py for sub-CC00134XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00134XX11 ses-44600 wang' returned non-zero exit status 1.
13/10/2023 00:46:56: Error in register_atlas.py for sub-CC00135AN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00135AN12 ses-44900 wang' returned non-zero exit status 1.
13/10/2023 00:46:57: Error in register_atlas.py for sub-CC00135BN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00135BN12 ses-44704 wang' returned non-zero exit status 1.
13/10/2023 00:46:58: Error in register_atlas.py for sub-CC00136AN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00136AN13 ses-45100 wang' returned non-zero exit status 1.
13/10/2023 00:46:59: Error in register_atlas.py for sub-CC00136BN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00136BN13 ses-45000 wang' returned non-zero exit status 1.
13/10/2023 00:47:00: Error in register_atlas.py for sub-CC00138XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00138XX15 ses-46200 wang' returned non-zero exit status 1.
13/10/2023 00:47:01: Error in register_atlas.py for sub-CC00139XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00139XX16 ses-49101 wang' returned non-zero exit status 1.
13/10/2023 00:47:02: Error in register_atlas.py for sub-CC00143AN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00143AN12 ses-47501 wang' returned non-zero exit status 1.
13/10/2023 00:47:04: Error in register_atlas.py for sub-CC00143BN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00143BN12 ses-47600 wang' returned non-zero exit status 1.
13/10/2023 00:47:05: Error in register_atlas.py for sub-CC00144XX13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00144XX13 ses-47701 wang' returned non-zero exit status 1.
13/10/2023 00:47:06: Error in register_atlas.py for sub-CC00145XX14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00145XX14 ses-48100 wang' returned non-zero exit status 1.
13/10/2023 00:47:07: Error in register_atlas.py for sub-CC00146XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00146XX15 ses-48400 wang' returned non-zero exit status 1.
13/10/2023 00:47:08: Error in register_atlas.py for sub-CC00147XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00147XX16 ses-48500 wang' returned non-zero exit status 1.
13/10/2023 00:47:09: Error in register_atlas.py for sub-CC00149XX18: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00149XX18 ses-49000 wang' returned non-zero exit status 1.
13/10/2023 00:47:10: Error in register_atlas.py for sub-CC00150AN02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00150AN02 ses-54800 wang' returned non-zero exit status 1.
13/10/2023 00:47:11: Error in register_atlas.py for sub-CC00150BN02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00150BN02 ses-49100 wang' returned non-zero exit status 1.
13/10/2023 00:47:12: Error in register_atlas.py for sub-CC00152AN04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00152AN04 ses-49200 wang' returned non-zero exit status 1.
13/10/2023 00:47:13: Error in register_atlas.py for sub-CC00153XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00153XX05 ses-50300 wang' returned non-zero exit status 1.
13/10/2023 00:47:14: Error in register_atlas.py for sub-CC00154XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00154XX06 ses-50700 wang' returned non-zero exit status 1.
13/10/2023 00:47:15: Error in register_atlas.py for sub-CC00155XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00155XX07 ses-51300 wang' returned non-zero exit status 1.
13/10/2023 00:47:16: Error in register_atlas.py for sub-CC00156XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00156XX08 ses-51500 wang' returned non-zero exit status 1.
13/10/2023 00:47:18: Error in register_atlas.py for sub-CC00157XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00157XX09 ses-51900 wang' returned non-zero exit status 1.
13/10/2023 00:47:19: Error in register_atlas.py for sub-CC00158XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00158XX10 ses-52200 wang' returned non-zero exit status 1.
13/10/2023 00:47:20: Error in register_atlas.py for sub-CC00159XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00159XX11 ses-52600 wang' returned non-zero exit status 1.
13/10/2023 00:47:21: Error in register_atlas.py for sub-CC00160XX04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00160XX04 ses-52700 wang' returned non-zero exit status 1.
13/10/2023 00:47:22: Error in register_atlas.py for sub-CC00161XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00161XX05 ses-53100 wang' returned non-zero exit status 1.
13/10/2023 00:47:23: Error in register_atlas.py for sub-CC00162XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00162XX06 ses-53600 wang' returned non-zero exit status 1.
13/10/2023 02:48:03: Error in register_vol_roi.py for sub-CC00088XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00088XX15 ses-31801 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:05: Error in register_vol_roi.py for sub-CC00089XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00089XX16 ses-32101 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:06: Error in register_vol_roi.py for sub-CC00091XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00091XX10 ses-32300 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:07: Error in register_vol_roi.py for sub-CC00094AN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00094AN13 ses-33500 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:08: Error in register_vol_roi.py for sub-CC00094BN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00094BN13 ses-33301 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:09: Error in register_vol_roi.py for sub-CC00095XX14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00095XX14 ses-33501 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:10: Error in register_vol_roi.py for sub-CC00096XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00096XX15 ses-33700 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:11: Error in register_vol_roi.py for sub-CC00097XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00097XX16 ses-33701 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:12: Error in register_vol_roi.py for sub-CC00098BN17: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00098BN17 ses-33900 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:13: Error in register_vol_roi.py for sub-CC00099AN18: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00099AN18 ses-34200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:14: Error in register_vol_roi.py for sub-CC00099BN18: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00099BN18 ses-34201 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:15: Error in register_vol_roi.py for sub-CC00100XX01: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00100XX01 ses-35000 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:16: Error in register_vol_roi.py for sub-CC00101XX02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00101XX02 ses-35001 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:18: Error in register_vol_roi.py for sub-CC00102XX03: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00102XX03 ses-35200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:19: Error in register_vol_roi.py for sub-CC00103XX04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00103XX04 ses-35300 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:20: Error in register_vol_roi.py for sub-CC00104XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00104XX05 ses-35800 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:21: Error in register_vol_roi.py for sub-CC00105XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00105XX06 ses-35801 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:22: Error in register_vol_roi.py for sub-CC00106XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00106XX07 ses-36100 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:23: Error in register_vol_roi.py for sub-CC00107XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00107XX08 ses-36300 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:24: Error in register_vol_roi.py for sub-CC00108XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00108XX09 ses-36800 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:25: Error in register_vol_roi.py for sub-CC00109XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00109XX10 ses-36901 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:26: Error in register_vol_roi.py for sub-CC00110XX03: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00110XX03 ses-37000 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:27: Error in register_vol_roi.py for sub-CC00111XX04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00111XX04 ses-37002 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:28: Error in register_vol_roi.py for sub-CC00112XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00112XX05 ses-37001 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:29: Error in register_vol_roi.py for sub-CC00113XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00113XX06 ses-37200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:30: Error in register_vol_roi.py for sub-CC00114XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00114XX07 ses-37100 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:32: Error in register_vol_roi.py for sub-CC00115XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00115XX08 ses-37801 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:33: Error in register_vol_roi.py for sub-CC00116XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00116XX09 ses-38001 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:34: Error in register_vol_roi.py for sub-CC00117XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00117XX10 ses-38200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:35: Error in register_vol_roi.py for sub-CC00118XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00118XX11 ses-39100 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:36: Error in register_vol_roi.py for sub-CC00119XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00119XX12 ses-39400 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:37: Error in register_vol_roi.py for sub-CC00120XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00120XX05 ses-41600 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:38: Error in register_vol_roi.py for sub-CC00121XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00121XX06 ses-41700 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:39: Error in register_vol_roi.py for sub-CC00122XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00122XX07 ses-42000 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:40: Error in register_vol_roi.py for sub-CC00124XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00124XX09 ses-42302 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:41: Error in register_vol_roi.py for sub-CC00126XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00126XX11 ses-43100 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:42: Error in register_vol_roi.py for sub-CC00127XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00127XX12 ses-43200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:43: Error in register_vol_roi.py for sub-CC00129AN14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00129AN14 ses-43500 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:45: Error in register_vol_roi.py for sub-CC00129BN14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00129BN14 ses-43701 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:46: Error in register_vol_roi.py for sub-CC00130XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00130XX07 ses-44001 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:47: Error in register_vol_roi.py for sub-CC00131XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00131XX08 ses-44200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:48: Error in register_vol_roi.py for sub-CC00132XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00132XX09 ses-44400 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:49: Error in register_vol_roi.py for sub-CC00133XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00133XX10 ses-44500 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:50: Error in register_vol_roi.py for sub-CC00134XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00134XX11 ses-44600 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:51: Error in register_vol_roi.py for sub-CC00135AN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00135AN12 ses-44900 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:52: Error in register_vol_roi.py for sub-CC00135BN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00135BN12 ses-44704 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:53: Error in register_vol_roi.py for sub-CC00136AN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00136AN13 ses-45100 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:54: Error in register_vol_roi.py for sub-CC00136BN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00136BN13 ses-45000 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:55: Error in register_vol_roi.py for sub-CC00138XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00138XX15 ses-46200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:56: Error in register_vol_roi.py for sub-CC00139XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00139XX16 ses-49101 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:57: Error in register_vol_roi.py for sub-CC00143AN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00143AN12 ses-47501 pulvinar' returned non-zero exit status 1.
13/10/2023 02:48:58: Error in register_vol_roi.py for sub-CC00143BN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00143BN12 ses-47600 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:00: Error in register_vol_roi.py for sub-CC00144XX13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00144XX13 ses-47701 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:01: Error in register_vol_roi.py for sub-CC00145XX14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00145XX14 ses-48100 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:02: Error in register_vol_roi.py for sub-CC00146XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00146XX15 ses-48400 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:03: Error in register_vol_roi.py for sub-CC00147XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00147XX16 ses-48500 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:04: Error in register_vol_roi.py for sub-CC00149XX18: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00149XX18 ses-49000 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:05: Error in register_vol_roi.py for sub-CC00150AN02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00150AN02 ses-54800 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:06: Error in register_vol_roi.py for sub-CC00150BN02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00150BN02 ses-49100 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:07: Error in register_vol_roi.py for sub-CC00152AN04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00152AN04 ses-49200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:08: Error in register_vol_roi.py for sub-CC00153XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00153XX05 ses-50300 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:09: Error in register_vol_roi.py for sub-CC00154XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00154XX06 ses-50700 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:10: Error in register_vol_roi.py for sub-CC00155XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00155XX07 ses-51300 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:11: Error in register_vol_roi.py for sub-CC00156XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00156XX08 ses-51500 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:12: Error in register_vol_roi.py for sub-CC00157XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00157XX09 ses-51900 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:13: Error in register_vol_roi.py for sub-CC00158XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00158XX10 ses-52200 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:14: Error in register_vol_roi.py for sub-CC00159XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00159XX11 ses-52600 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:16: Error in register_vol_roi.py for sub-CC00160XX04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00160XX04 ses-52700 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:17: Error in register_vol_roi.py for sub-CC00161XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00161XX05 ses-53100 pulvinar' returned non-zero exit status 1.
13/10/2023 02:49:18: Error in register_vol_roi.py for sub-CC00162XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00162XX06 ses-53600 pulvinar' returned non-zero exit status 1.
13/10/2023 10:08:13: Error in register_atlas.py for sub-CC00119XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00119XX12 ses-39400 wang' returned non-zero exit status 1.
13/10/2023 10:08:14: Error in register_atlas.py for sub-CC00120XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00120XX05 ses-41600 wang' returned non-zero exit status 1.
13/10/2023 10:08:15: Error in register_atlas.py for sub-CC00121XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_atlas.py sub-CC00121XX06 ses-41700 wang' returned non-zero exit status 1.
13/10/2023 10:12:02: Error in extract_brain.py for sub-CC00056XX07: [Errno 13] Permission denied: '/mnt/e/dhcp_analysis_full/participants.csv'
13/10/2023 19:23:59: Error in register_vol_roi.py for sub-CC00088XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00088XX15 ses-31801 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:00: Error in register_vol_roi.py for sub-CC00089XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00089XX16 ses-32101 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:01: Error in register_vol_roi.py for sub-CC00091XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00091XX10 ses-32300 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:02: Error in register_vol_roi.py for sub-CC00094AN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00094AN13 ses-33500 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:03: Error in register_vol_roi.py for sub-CC00094BN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00094BN13 ses-33301 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:04: Error in register_vol_roi.py for sub-CC00095XX14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00095XX14 ses-33501 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:05: Error in register_vol_roi.py for sub-CC00096XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00096XX15 ses-33700 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:06: Error in register_vol_roi.py for sub-CC00097XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00097XX16 ses-33701 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:07: Error in register_vol_roi.py for sub-CC00098BN17: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00098BN17 ses-33900 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:09: Error in register_vol_roi.py for sub-CC00099AN18: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00099AN18 ses-34200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:10: Error in register_vol_roi.py for sub-CC00099BN18: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00099BN18 ses-34201 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:11: Error in register_vol_roi.py for sub-CC00100XX01: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00100XX01 ses-35000 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:12: Error in register_vol_roi.py for sub-CC00101XX02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00101XX02 ses-35001 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:13: Error in register_vol_roi.py for sub-CC00102XX03: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00102XX03 ses-35200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:14: Error in register_vol_roi.py for sub-CC00103XX04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00103XX04 ses-35300 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:15: Error in register_vol_roi.py for sub-CC00104XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00104XX05 ses-35800 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:16: Error in register_vol_roi.py for sub-CC00105XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00105XX06 ses-35801 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:17: Error in register_vol_roi.py for sub-CC00106XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00106XX07 ses-36100 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:18: Error in register_vol_roi.py for sub-CC00107XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00107XX08 ses-36300 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:19: Error in register_vol_roi.py for sub-CC00108XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00108XX09 ses-36800 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:20: Error in register_vol_roi.py for sub-CC00109XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00109XX10 ses-36901 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:21: Error in register_vol_roi.py for sub-CC00110XX03: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00110XX03 ses-37000 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:22: Error in register_vol_roi.py for sub-CC00111XX04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00111XX04 ses-37002 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:23: Error in register_vol_roi.py for sub-CC00112XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00112XX05 ses-37001 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:24: Error in register_vol_roi.py for sub-CC00113XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00113XX06 ses-37200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:25: Error in register_vol_roi.py for sub-CC00114XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00114XX07 ses-37100 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:26: Error in register_vol_roi.py for sub-CC00115XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00115XX08 ses-37801 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:27: Error in register_vol_roi.py for sub-CC00116XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00116XX09 ses-38001 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:28: Error in register_vol_roi.py for sub-CC00117XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00117XX10 ses-38200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:29: Error in register_vol_roi.py for sub-CC00118XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00118XX11 ses-39100 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:30: Error in register_vol_roi.py for sub-CC00119XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00119XX12 ses-39400 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:31: Error in register_vol_roi.py for sub-CC00120XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00120XX05 ses-41600 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:32: Error in register_vol_roi.py for sub-CC00121XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00121XX06 ses-41700 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:34: Error in register_vol_roi.py for sub-CC00122XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00122XX07 ses-42000 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:35: Error in register_vol_roi.py for sub-CC00124XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00124XX09 ses-42302 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:36: Error in register_vol_roi.py for sub-CC00126XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00126XX11 ses-43100 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:37: Error in register_vol_roi.py for sub-CC00127XX12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00127XX12 ses-43200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:38: Error in register_vol_roi.py for sub-CC00129AN14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00129AN14 ses-43500 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:39: Error in register_vol_roi.py for sub-CC00129BN14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00129BN14 ses-43701 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:40: Error in register_vol_roi.py for sub-CC00130XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00130XX07 ses-44001 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:41: Error in register_vol_roi.py for sub-CC00131XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00131XX08 ses-44200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:42: Error in register_vol_roi.py for sub-CC00132XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00132XX09 ses-44400 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:43: Error in register_vol_roi.py for sub-CC00133XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00133XX10 ses-44500 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:44: Error in register_vol_roi.py for sub-CC00134XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00134XX11 ses-44600 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:45: Error in register_vol_roi.py for sub-CC00135AN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00135AN12 ses-44900 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:46: Error in register_vol_roi.py for sub-CC00135BN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00135BN12 ses-44704 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:47: Error in register_vol_roi.py for sub-CC00136AN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00136AN13 ses-45100 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:48: Error in register_vol_roi.py for sub-CC00136BN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00136BN13 ses-45000 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:49: Error in register_vol_roi.py for sub-CC00138XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00138XX15 ses-46200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:50: Error in register_vol_roi.py for sub-CC00139XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00139XX16 ses-49101 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:51: Error in register_vol_roi.py for sub-CC00143AN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00143AN12 ses-47501 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:52: Error in register_vol_roi.py for sub-CC00143BN12: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00143BN12 ses-47600 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:53: Error in register_vol_roi.py for sub-CC00144XX13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00144XX13 ses-47701 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:54: Error in register_vol_roi.py for sub-CC00145XX14: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00145XX14 ses-48100 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:55: Error in register_vol_roi.py for sub-CC00146XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00146XX15 ses-48400 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:56: Error in register_vol_roi.py for sub-CC00147XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00147XX16 ses-48500 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:57: Error in register_vol_roi.py for sub-CC00149XX18: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00149XX18 ses-49000 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:58: Error in register_vol_roi.py for sub-CC00150AN02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00150AN02 ses-54800 pulvinar' returned non-zero exit status 1.
13/10/2023 19:24:59: Error in register_vol_roi.py for sub-CC00150BN02: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00150BN02 ses-49100 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:00: Error in register_vol_roi.py for sub-CC00152AN04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00152AN04 ses-49200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:01: Error in register_vol_roi.py for sub-CC00153XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00153XX05 ses-50300 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:02: Error in register_vol_roi.py for sub-CC00154XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00154XX06 ses-50700 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:04: Error in register_vol_roi.py for sub-CC00155XX07: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00155XX07 ses-51300 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:05: Error in register_vol_roi.py for sub-CC00156XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00156XX08 ses-51500 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:06: Error in register_vol_roi.py for sub-CC00157XX09: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00157XX09 ses-51900 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:07: Error in register_vol_roi.py for sub-CC00158XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00158XX10 ses-52200 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:08: Error in register_vol_roi.py for sub-CC00159XX11: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00159XX11 ses-52600 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:09: Error in register_vol_roi.py for sub-CC00160XX04: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00160XX04 ses-52700 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:10: Error in register_vol_roi.py for sub-CC00161XX05: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00161XX05 ses-53100 pulvinar' returned non-zero exit status 1.
13/10/2023 19:25:11: Error in register_vol_roi.py for sub-CC00162XX06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00162XX06 ses-53600 pulvinar' returned non-zero exit status 1.
14/10/2023 11:42:21: Error in register_vol_roi.py for sub-CC00088XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00088XX15 ses-31801 pulvinar' returned non-zero exit status 1.
14/10/2023 11:42:23: Error in register_vol_roi.py for sub-CC00089XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00089XX16 ses-32101 pulvinar' returned non-zero exit status 1.
14/10/2023 11:42:24: Error in register_vol_roi.py for sub-CC00091XX10: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00091XX10 ses-32300 pulvinar' returned non-zero exit status 1.
14/10/2023 11:42:26: Error in register_vol_roi.py for sub-CC00094AN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00094AN13 ses-33500 pulvinar' returned non-zero exit status 1.
14/10/2023 11:42:27: Error in register_vol_roi.py for sub-CC00094BN13: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00094BN13 ses-33301 pulvinar' returned non-zero exit status 1.
14/10/2023 11:42:54: Error in register_vol_roi.py for sub-CC00088XX15: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00088XX15 ses-31801 pulvinar' returned non-zero exit status 1.
14/10/2023 11:42:56: Error in register_vol_roi.py for sub-CC00089XX16: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00089XX16 ses-32101 pulvinar' returned non-zero exit status 1.
15/10/2023 11:35:21: Error in register_vol_roi.py for sub-CC00107XX08: [Errno 13] Permission denied: '/mnt/e/dhcp_analysis_full/participants.csv'
22/11/2023 11:22:36: Error in extract_brain.py for sub-CC00056XX07: [Errno 13] Permission denied: '/mnt/e/dhcp_analysis_full/participants.csv'
13/02/2024 16:23:34: Error in register_vol_roi.py for sub-CC00063AN06: [Errno 13] Permission denied: '/mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/participants.csv'
13/02/2024 16:23:44: Error in register_vol_roi.py for sub-CC00065XX08: [Errno 13] Permission denied: '/mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/participants.csv'
13/02/2024 17:06:35: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:06:36: Error in extract_ts_voxel.py for sub-CC00065XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00065XX08 ses-18600 pulvinar' returned non-zero exit status 1.
13/02/2024 17:11:30: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:11:53: Error in extract_ts_voxel.py for sub-CC00065XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00065XX08 ses-18600 pulvinar' returned non-zero exit status 1.
13/02/2024 17:23:19: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:23:24: Error in extract_ts_voxel.py for sub-CC00065XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00065XX08 ses-18600 pulvinar' returned non-zero exit status 1.
13/02/2024 17:23:39: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:27:10: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:29:32: Error in register_vol_roi.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:29:34: Error in register_vol_roi.py for sub-CC00065XX08: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00065XX08 ses-18600 pulvinar' returned non-zero exit status 1.
13/02/2024 17:32:26: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:32:44: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:33:44: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:48:03: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:48:27: Error in register_vol_roi.py for sub-CC00063AN06: [Errno 13] Permission denied: '/mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/participants.csv'
13/02/2024 17:49:18: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
13/02/2024 17:51:18: Error in extract_ts_voxel.py for sub-CC00063AN06: Command 'python /mnt/c/Users/ArcaroLab/Desktop/git_repos/dhcp/fmri/extract_ts_voxel.py sub-CC00063AN06 ses-15102 pulvinar' returned non-zero exit status 1.
26/04/2024 19:32:31: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
26/04/2024 19:32:31: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
26/04/2024 19:32:31: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
26/04/2024 19:32:32: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
26/04/2024 19:32:32: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
26/04/2024 19:32:54: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
26/04/2024 19:32:55: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
26/04/2024 19:32:56: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
26/04/2024 19:36:10: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
26/04/2024 19:36:27: Error in extract_brain.py for sub-CC00063AN06: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00063AN06 ses-15102 ' returned non-zero exit status 1.
26/04/2024 19:39:04: Error in extract_brain.py for sub-CC00056XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00056XX07 ses-10700 ' returned non-zero exit status 1.
26/04/2024 19:42:29: Error in extract_brain.py for sub-CC00056XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00056XX07 ses-10700 ' returned non-zero exit status 1.
26/04/2024 19:44:31: Error in extract_brain.py for sub-CC00056XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00056XX07 ses-10700 ' returned non-zero exit status 1.
26/04/2024 19:44:46: Error in extract_brain.py for sub-CC00056XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00056XX07 ses-10700 ' returned non-zero exit status 1.
26/04/2024 19:45:27: Error in extract_brain.py for sub-CC00058XX09: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00058XX09 ses-11300 ' returned non-zero exit status 1.
26/04/2024 19:45:36: Error in extract_brain.py for sub-CC00063BN06: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00063BN06 ses-15104 ' returned non-zero exit status 1.
26/04/2024 19:46:04: Error in extract_brain.py for sub-CC00070XX05: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00070XX05 ses-26700 ' returned non-zero exit status 1.
26/04/2024 19:46:09: Error in extract_brain.py for sub-CC00072XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00072XX07 ses-27600 ' returned non-zero exit status 1.
26/04/2024 19:48:15: Error in extract_brain.py for sub-CC00058XX09: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00058XX09 ses-11300 ' returned non-zero exit status 1.
26/04/2024 19:48:16: Error in extract_brain.py for sub-CC00063BN06: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00063BN06 ses-15104 ' returned non-zero exit status 1.
27/04/2024 17:16:31: Error in extract_brain.py for sub-CC00057XX08: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00057XX08 ses-11002 ' returned non-zero exit status 1.
27/04/2024 17:16:32: Error in extract_brain.py for sub-CC00058XX09: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00058XX09 ses-11300 ' returned non-zero exit status 1.
27/04/2024 17:17:23: Error in extract_brain.py for sub-CC00057XX08: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00057XX08 ses-11002 ' returned non-zero exit status 1.
27/04/2024 17:17:45: Error in extract_brain.py for sub-CC00056XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00056XX07 ses-10700 ' returned non-zero exit status 1.
27/04/2024 17:18:15: Error in extract_brain.py for sub-CC00056XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00056XX07 ses-10700 ' returned non-zero exit status 1.
27/04/2024 17:32:57: Error in extract_brain.py for sub-CC00058XX09: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00058XX09 ses-11300 ' returned non-zero exit status 1.
27/04/2024 17:33:06: Error in extract_brain.py for sub-CC00063BN06: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00063BN06 ses-15104 ' returned non-zero exit status 1.
27/04/2024 17:33:31: Error in extract_brain.py for sub-CC00070XX05: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00070XX05 ses-26700 ' returned non-zero exit status 1.
27/04/2024 17:33:36: Error in extract_brain.py for sub-CC00072XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00072XX07 ses-27600 ' returned non-zero exit status 1.
27/04/2024 17:34:16: Error in extract_brain.py for sub-CC00084XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00084XX11 ses-31201 ' returned non-zero exit status 1.
27/04/2024 17:35:00: Error in extract_brain.py for sub-CC00097XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00097XX16 ses-33701 ' returned non-zero exit status 1.
27/04/2024 17:35:01: Error in extract_brain.py for sub-CC00098BN17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00098BN17 ses-33900 ' returned non-zero exit status 1.
27/04/2024 17:35:22: Error in extract_brain.py for sub-CC00103XX04: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00103XX04 ses-35300 ' returned non-zero exit status 1.
27/04/2024 17:35:46: Error in extract_brain.py for sub-CC00110XX03: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00110XX03 ses-37000 ' returned non-zero exit status 1.
27/04/2024 17:36:14: Error in extract_brain.py for sub-CC00118XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00118XX11 ses-39100 ' returned non-zero exit status 1.
27/04/2024 17:37:32: Error in extract_brain.py for sub-CC00143AN12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00143AN12 ses-47501 ' returned non-zero exit status 1.
27/04/2024 17:38:20: Error in extract_brain.py for sub-CC00156XX08: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00156XX08 ses-51500 ' returned non-zero exit status 1.
27/04/2024 17:38:46: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
27/04/2024 17:38:48: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
27/04/2024 17:38:50: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
27/04/2024 17:38:52: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
27/04/2024 17:38:53: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
27/04/2024 17:38:55: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
27/04/2024 17:38:57: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
27/04/2024 17:38:59: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
27/04/2024 17:39:01: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
27/04/2024 17:39:02: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
27/04/2024 17:39:04: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
27/04/2024 17:39:06: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
27/04/2024 17:39:08: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
27/04/2024 17:39:10: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
27/04/2024 17:39:12: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
27/04/2024 17:39:14: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
27/04/2024 17:39:16: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
27/04/2024 17:39:18: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
27/04/2024 17:39:20: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
27/04/2024 17:39:21: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
27/04/2024 17:39:23: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
27/04/2024 17:39:25: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
27/04/2024 17:39:27: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
27/04/2024 17:39:29: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
27/04/2024 17:39:30: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
28/04/2024 17:50:31: Error in extract_brain.py for sub-CC00058XX09: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00058XX09 ses-11300 ' returned non-zero exit status 1.
28/04/2024 17:50:41: Error in extract_brain.py for sub-CC00063BN06: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00063BN06 ses-15104 ' returned non-zero exit status 1.
28/04/2024 17:51:08: Error in extract_brain.py for sub-CC00070XX05: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00070XX05 ses-26700 ' returned non-zero exit status 1.
28/04/2024 17:51:13: Error in extract_brain.py for sub-CC00072XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00072XX07 ses-27600 ' returned non-zero exit status 1.
28/04/2024 17:51:56: Error in extract_brain.py for sub-CC00084XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00084XX11 ses-31201 ' returned non-zero exit status 1.
28/04/2024 17:52:42: Error in extract_brain.py for sub-CC00097XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00097XX16 ses-33701 ' returned non-zero exit status 1.
28/04/2024 17:52:44: Error in extract_brain.py for sub-CC00098BN17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00098BN17 ses-33900 ' returned non-zero exit status 1.
28/04/2024 17:53:05: Error in extract_brain.py for sub-CC00103XX04: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00103XX04 ses-35300 ' returned non-zero exit status 1.
28/04/2024 17:53:32: Error in extract_brain.py for sub-CC00110XX03: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00110XX03 ses-37000 ' returned non-zero exit status 1.
28/04/2024 17:54:02: Error in extract_brain.py for sub-CC00118XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00118XX11 ses-39100 ' returned non-zero exit status 1.
28/04/2024 17:55:24: Error in extract_brain.py for sub-CC00143AN12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00143AN12 ses-47501 ' returned non-zero exit status 1.
28/04/2024 17:56:14: Error in extract_brain.py for sub-CC00156XX08: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00156XX08 ses-51500 ' returned non-zero exit status 1.
28/04/2024 17:56:40: Error in extract_brain.py for sub-CC00852XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00852XX11 ses-28210 ' returned non-zero exit status 1.
28/04/2024 17:56:42: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
28/04/2024 17:56:45: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
28/04/2024 17:56:47: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
28/04/2024 17:56:49: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
28/04/2024 17:56:50: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
28/04/2024 17:56:52: Error in extract_brain.py for sub-CC00852XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00852XX11 ses-28210 ' returned non-zero exit status 1.
28/04/2024 17:56:54: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
28/04/2024 17:56:56: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
28/04/2024 17:56:59: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
28/04/2024 17:57:01: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
28/04/2024 17:57:02: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
28/04/2024 17:57:04: Error in extract_brain.py for sub-CC00852XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00852XX11 ses-28210 ' returned non-zero exit status 1.
28/04/2024 17:57:06: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
28/04/2024 17:57:08: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
28/04/2024 17:57:10: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
28/04/2024 17:57:12: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
28/04/2024 17:57:14: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
28/04/2024 17:57:16: Error in extract_brain.py for sub-CC00852XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00852XX11 ses-28210 ' returned non-zero exit status 1.
28/04/2024 17:57:18: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
28/04/2024 17:57:20: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
28/04/2024 17:57:22: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
28/04/2024 17:57:24: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
28/04/2024 17:57:26: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
28/04/2024 17:57:28: Error in extract_brain.py for sub-CC00852XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00852XX11 ses-28210 ' returned non-zero exit status 1.
28/04/2024 17:57:30: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
28/04/2024 17:57:32: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
28/04/2024 17:57:34: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
28/04/2024 17:57:36: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
28/04/2024 17:57:37: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
28/04/2024 17:57:39: Error in extract_brain.py for sub-CC00853XX12: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00853XX12 ses-7330 ' returned non-zero exit status 1.
28/04/2024 17:57:41: Error in extract_brain.py for sub-CC00858XX17: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00858XX17 ses-32210 ' returned non-zero exit status 1.
28/04/2024 17:57:43: Error in extract_brain.py for sub-CC00860XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00860XX11 ses-7030 ' returned non-zero exit status 1.
28/04/2024 17:57:45: Error in extract_brain.py for sub-CC00871XX14: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00871XX14 ses-38810 ' returned non-zero exit status 1.
28/04/2024 17:57:47: Error in extract_brain.py for sub-CC00907XX16: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/extract_brain.py sub-CC00907XX16 ses-19230 ' returned non-zero exit status 1.
05/05/2024 13:15:07: Error in register_vol_roi.py for sub-CC00056XX07: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00056XX07 ses-10700 pulvinar' returned non-zero exit status 1.
05/05/2024 13:15:08: Error in register_vol_roi.py for sub-CC00057XX08: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00057XX08 ses-11002 pulvinar' returned non-zero exit status 1.
05/05/2024 13:15:09: Error in register_vol_roi.py for sub-CC00060XX03: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00060XX03 ses-12501 pulvinar' returned non-zero exit status 1.
05/05/2024 13:44:01: Error in register_vol_roi.py for sub-CC00852XX11: Command 'python /mnt/DataDrive2/vlad/git_repos/dhcp/fmri/register_vol_roi.py sub-CC00852XX11 ses-28210 pulvinar' returned non-zero exit status 1.
